CREATE TABLE IF NOT EXISTS USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FISRT_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    PUBLIC_KEY TEXT NOT NULL,
    PRIVATE_KEY TEXT NOT NULL
)